version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    restart: always
    environment:
      - "discovery.type=single-node"  # configuration pour un seul nœud
      - "xpack.security.enabled=false"  # désactive la sécurité (si nécessaire)
    ports:
      - "9200:9200"  # expose le port 9200 pour accéder à Elasticsearch
      - "9300:9300"  # expose le port 9300 pour la communication entre nœuds (utile si vous avez plusieurs nœuds)
    networks:
      - elnet
    volumes:
      - esdata:/usr/share/elasticsearch/data  # volume pour persister les données Elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    restart: always
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"  # adresse d'Elasticsearch
    ports:
      - "5601:5601"  # expose le port 5601 pour accéder à Kibana
    depends_on:
      - elasticsearch  # Kibana dépend d'Elasticsearch pour démarrer
    networks:
      - elnet

networks:
  elnet:
    driver: bridge

volumes:
  esdata:
    driver: local
